/**
 * TodoList
 * Simple TodoList App created with the help of Swagger Editor
 *
 * OpenAPI spec version: 1.0.11
 * Contact: veronicaxlcw@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.api;

import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;
import io.swagger.model.Todo;
import org.apache.cxf.jaxrs.client.ClientConfiguration;
import org.apache.cxf.jaxrs.client.JAXRSClientFactory;
import org.apache.cxf.jaxrs.client.WebClient;
import org.junit.Before;
import org.junit.Test;

import java.util.ArrayList;
import java.util.List;




/**
 * TodoList
 *
 * <p>Simple TodoList App created with the help of Swagger Editor
 *
 * API tests for TodosApi 
 */
public class TodosApiTest {


    private TodosApi api;
    
    @Before
    public void setup() {
        JacksonJsonProvider provider = new JacksonJsonProvider();
        List providers = new ArrayList();
        providers.add(provider);
        
        api = JAXRSClientFactory.create("https://todolist.swagger.io/api/v3", TodosApi.class, providers);
        org.apache.cxf.jaxrs.client.Client client = WebClient.client(api);
        
        ClientConfiguration config = WebClient.getConfig(client); 
    }

    /**
     * Add a new todo to the todo list
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addTodoTest() {
        String name = null;
        String description = null;
        Long dueDate = null;
        Long status = null;
        Todo body = null;
        //Todo response = api.addTodo(name, description, dueDate, status, body);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    /**
     * Create a new todo list under the userId
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTodosTest() {
        List<Todo> body = null;
        //List<Todo> response = api.createTodos(body);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    /**
     * Filter the todos by due date
     *
     * Filter the todos by the due date inputted
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void filterTest() {
        Integer duedate = null;
        //List<Todo> response = api.filter(duedate);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    /**
     * Deletes a todo
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeTodoTest() {
        String name = null;
        String description = null;
        Long dueDate = null;
        Long status = null;
        //api.removeTodo(name, description, dueDate, status);
        
        // TODO: test validations
        
        
    }
    /**
     * Sort the todo list by due date
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sortTest() {
        //List<Todo> response = api.sort();
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
}
